title: "Tech Blogs from a Silent Warrior"
name: "Sachin"
description: "Notes and explorations across Cloud Infrastructure, AI Systems, and Distributed Architecture."
remote_theme: "mmistakes/minimal-mistakes"
include:
  - _pages

# Site settings
url: "https://thesilentwarrior.org"
baseurl: ""

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-G0968414TJ"
    anonymize_ip: true

google_site_verification: KefY_ZWqzA3q_Uxxlf5eZa7d6g1H0xSPPg-VcgbdlBA

# Build settings
markdown: kramdown

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
  
# Minimal Mistakes settings
locale: "en-US"
logo: "/assets/images/silentWarrorDP.png"
link_color: "#2a7ae2"
search: true
search_full_content: true
breadcrumbs: true
read_time: true
words_per_minute: 200

og_image: "/assets/images/sw_og.jpg"
minimal_mistakes_skin: "contrast"

author:
  name: "Silent Warrior"
  avatar: "/assets/images/silentWarrorDP.png"
  bio: "A knowledge seeker fighting the lazy mind to learn and build something new every day."
  links:
    - label: "Codeberg: silentwarrior"
      icon: "fab fa-git-alt"
      url: "https://codeberg.org/silentwarrior"

    - label: "Philosophical Blogs"
      icon: "fas fa-fire"
      url: "https://thesilentwarrior.org/path-of-the-silent-warrior/"

    - label: "sachin-sharma-b36b596"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sachin-sharma-b36b596"

    - label: "@swsilentwarrior"
      icon: "fab fa-twitter"   # safer than fa-x-twitter
      url: "https://x.com/swsilentwarrior"

    - label: "contact.silentwarrior@proton.me"
      icon: "fas fa-envelope"
      url: "mailto:contact.silentwarrior@proton.me"
